[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-undefined",
    "-C",
    "link-arg=dynamic_lookup",
    # "-Zshare-generics=y",
    # "-Zthreads=0",
]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
